from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List


EXCLUDE_DIRS = [
    ".git", ".hg", ".svn", ".idea", ".vscode", ".gradle", ".mvn",
    "node_modules", "vendor", "third_party", "build", "dist", "out", "target",
    "bin", "obj", "coverage", "__pycache__", ".codewiki",
]
EXCLUDE_GLOBS = ["*.class", "*.jar", "*.war", "*.zip", "*.db", "*.sqlite", "*.sqlite3"]
GENERATED_MARKERS = [
    "code generated by", "@generated", "autogenerated", "auto-generated",
    "this class was generated", "this file was generated", "generated automatically",
    "generated by protoc", "swagger-codegen", "openapi-generator", "jooq", "sqlc",
]
GENERATED_WEAK_MARKERS = ["do not edit", "do not modify"]
WEAK_MARKER_MAX_LINE = 25
TEST_DIR_NAMES = {"test", "tests", "spec", "specs", "__tests__", "testdata", "fixtures"}
LANGUAGES = {".java": "java", ".xml": "xml", ".sql": "sql", ".properties": "properties"}


@dataclass
class Config:
    exclude_dirs: List[str] = field(default_factory=lambda: list(EXCLUDE_DIRS))
    exclude_globs: List[str] = field(default_factory=lambda: list(EXCLUDE_GLOBS))
    languages: Dict[str, str] = field(default_factory=lambda: dict(LANGUAGES))
    max_file_bytes: int = 1500000

