from __future__ import annotations

import os
import tempfile
from typing import Dict


FIXTURE_FILES = {
    "src/com/acme/OrderService.java": (
        "package com.acme;\n"
        "\n"
        "public class OrderService {\n"
        "    public OrderService() {}\n"
        "    public OrderService(String source) {}\n"
        "    public void cancel(String orderId) {\n"
        "    }\n"
        "    public void cancel(String orderId, int reason) {\n"
        "    }\n"
        "    static class Audit {\n"
        "        class Entry {\n"
        "            void record(String value) {}\n"
        "        }\n"
        "    }\n"
        "    public void multiline(\n"
        "        String orderId,\n"
        "        int reason\n"
        "    ) {\n"
        "    }\n"
        "    public void wrapped(\n"
        "        String orderId\n"
        "    ) {}\n"
        "    public void wrapped(\n"
        "        String orderId,\n"
        "        int reason\n"
        "    ) {}\n"
        "}\n"
    ),
    "src/com/acme/OrderDao.java": (
        "package com.acme;\n"
        "public interface OrderDao {\n"
        "    void save(String orderId);\n"
        "}\n"
    ),
    "src/com/acme/OrderRepository.java": (
        "package com.acme;\n"
        "public class OrderRepository implements OrderDao {\n"
        "    public void save(String orderId) {}\n"
        "}\n"
    ),
    "src/com/acme/Order.java": "package com.acme;\npublic class Order {}\n",
    "src/com/other/Order.java": (
        "package com.other;\n"
        "public class Order {\n"
        "}\n"
    ),
    "generated/Generated.java": (
        "// Code generated by fixture; DO NOT EDIT.\n"
        "package generated;\n"
        "public class Generated { void generatedMethod() {} }\n"
    ),
    "tests/java/TestOrder.java": (
        "package tests.java;\n"
        "public class TestOrder { void testOrder() {} }\n"
    ),
    "config/application.xml": "<application/>\n",
    "db/schema.sql": "create table orders(id integer);\n",
    "config/application.properties": "service.name=orders\n",
}


def write_fixture(root: str) -> Dict[str, bytes]:
    written = {}
    for rel_path, source in FIXTURE_FILES.items():
        path = os.path.join(root, rel_path)
        parent = os.path.dirname(path)
        if not os.path.isdir(parent):
            os.makedirs(parent)
        raw = source.encode("utf-8")
        with open(path, "wb") as stream:
            stream.write(raw)
        written[rel_path] = raw
    return written


def fixture_directory():
    return tempfile.TemporaryDirectory(prefix="codewiki-test-")
