from __future__ import annotations

import os
import unittest

from tests.fixture import fixture_directory, write_fixture


class ScanTests(unittest.TestCase):
    def test_records_java_and_non_java_metadata_and_detects_generated_and_test(self):
        from codewiki.config import Config
        from codewiki.index.scan import analyzable, scan

        with fixture_directory() as root:
            write_fixture(root)
            records, skipped = scan(root, Config())
            by_path = {record.path: record for record in records}
            self.assertEqual({
                "java", "xml", "sql", "properties",
            }, {record.language for record in records})
            self.assertTrue(by_path["generated/Generated.java"].is_generated)
            self.assertTrue(by_path["tests/java/TestOrder.java"].is_test)
            self.assertEqual(["generated/Generated.java"], [
                record.path for record in analyzable(records)
                if record.path == "generated/Generated.java"
            ])
            self.assertNotIn("generated", skipped)
            self.assertEqual(sorted(record.path for record in records), [
                record.path for record in records
            ])

    def test_generated_java_is_persisted_with_symbols(self):
        from codewiki.index import pipeline
        from codewiki.store.db import open_index

        with fixture_directory() as root:
            path = os.path.join(root, "Generated.java")
            with open(path, "w", encoding="utf-8") as stream:
                stream.write(
                    "// Code generated by tool\n"
                    "package demo;\n"
                    "public class Generated { void generatedMethod() {} }\n"
                )

            result = pipeline.run(root, os.path.join(root, "out"), jobs=1)
            connection = open_index(result.db_path)
            try:
                file_id, is_generated = connection.execute(
                    "SELECT file_id, is_generated FROM files "
                    "WHERE path = 'Generated.java'"
                ).fetchone()
                symbol_count = connection.execute(
                    "SELECT count(*) FROM symbols WHERE file_id = ?",
                    (file_id,),
                ).fetchone()[0]
            finally:
                connection.close()

            self.assertEqual(1, is_generated)
            self.assertGreater(symbol_count, 0)

    def test_read_text_uses_repository_relative_path(self):
        from codewiki.config import Config
        from codewiki.index.scan import read_text, scan

        with fixture_directory() as root:
            write_fixture(root)
            records, _ = scan(root, Config())
            java = next(record for record in records if record.path.endswith("Order.java"))
            self.assertIn("class Order", read_text(root, java.path))
            self.assertFalse(os.path.isabs(java.path))


if __name__ == "__main__":
    unittest.main()
